---
- name: Configure interfaceconfig
  hosts: cisco_ios
  gather_facts: no

  vars: 
    loopback_ip: 1.1.1.1

  tasks:
    - name: configure loopback interface
      cisco.ios.ios_config:
        lines:
           - ip address {{ loopback_ip }} 255.255.255.0
           - description Configured-with-ansible
        parents: interface Loopback0
