---
- name: add static route to router
  hosts: cisco_ios_xe
  connection: local
  vars_files:
    - login_info.yaml

  tasks:
    - name: add static route
      iosxe_static_route:
        ipv4_network: "10.5.5.0"  
        ipv4_netmask: "255.255.255.0"  
        ipv4_nexthop: "192.168.1.1"
        name: "Ansible"
        state: "present"
        vrf:     
        username: "{{ username }}"
        password: "{{ password }}"
        host: "{{ inventory_hostname }}"
