---
- name: save running configuration to startup configuration
  hosts: cisco_ios_xe
  connection: local  
  vars_files:
    - login_info.yaml

  tasks:
    - name: save configuration in router
      iosxe_save_config:
        username: "{{ username }}"
        password: "{{ password }}"
        host: "{{ inventory_hostname }}"
