---
- name: get facts from router
  hosts: cisco_ios_xe
  connection: local
  vars_files:
    - login_info.yaml    

  tasks:
    - name: get facts from router
      iosxe_get_facts:
        username: "{{ username }}"
        password: "{{ password }}"
        host: "{{ inventory_hostname }}"
      register: facts_dict
    - name: format output
      debug: 
        msg: "{{ facts_dict.items() }}"
