---
- name: Login SDWAN
  hosts: cisco_sdwan
  connection: local

  tasks:
    - name: Login to the vManage
      uri:
        url: https://{{ansible_host}}/j_security_check
        method: POST
        body: "j_username={{username}}&j_password={{password}}"
        validate_certs: no
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: login

    - name: print login_info
      debug:
        msg: "{{ login }}"