---
- name: Query meraki orgs
  hosts: meraki
  connection: local

  tasks:
    - name: Create a new organization named YourOrg
      meraki_organization:
        auth_key: 05599027d3ef1887c3593500a20b40aada21dde2
        org_name: CiscoSEC
        state: present
        
    - name: Query information about a single organization named YourOrg
      meraki_organization:
        auth_key: 05599027d3ef1887c3593500a20b40aada21dde2
        org_name: CiscoSEC
        state: query
      register: org_info

    - name: print org_info
      debug:
        msg: "{{ org_info }}"